version: '3.8'

services:
  web:
    image: baiban_e2e_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - ./media:/media
      - ./static:/static
    depends_on:
      - db
    command: /bin/bash -c "pip install -r requirements_dev.txt; python tasks.py"
    env_file:
      - ./config/env_vars/db/dev_e2e_db.env
    environment:
      - ENV=dev
    tty: true

  frontend:
    image: baiban_e2e_frontend
    build:
      context: frontend
    volumes:
      - ./frontend:/srv/client
    command: /bin/bash -c "npm i; npm run serve"

  db:
    image: postgres:13
    env_file:
      - ./config/env_vars/db/dev_e2e_db.env

  nginx:
    image: nginx:1.17.4
    depends_on:
      - web
      - frontend
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media:ro
      - ./static:/static:ro
    command:
      /bin/bash -c "nginx -g 'daemon off;'"

  cypress:
    image: cypress/included:3.2.0
    volumes:
      - ./frontend/tests/e2e:/e2e
      - ./scripts:/scripts
    depends_on:
      - web
      - frontend
      - nginx
    environment:
      - CYPRESS_baseUrl=http://nginx:80
    entrypoint:
      /scripts/wait-for-it.sh frontend:8080 -- cypress run
    working_dir: '/e2e'

networks:
  default:
    external:
      name: baiban_e2e_tests
