version: '3.8'

services:
  web:
    image: baiban_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - ./media:/media
      - ./static:/static
    depends_on:
      - db
    command: /bin/bash -c "pip install -r requirements_dev.txt; python tasks.py"
    env_file:
      - ./config/env_vars/db/dev_db.env
      - .env
    tty: true

  frontend:
    image: baiban_frontend
    build:
      context: frontend
    volumes:
      - ./frontend:/srv/client
    expose:
      - "3000"
    command: /bin/bash -c "npm i; npm run serve"

  db:
    image: postgres:13
    env_file:
      - ./config/env_vars/db/dev_db.env
    ports:
      - '5432:5432'

  nginx:
    image: nginx:1.17.4
    depends_on:
      - web
      - frontend
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media:ro
      - ./static:/static:ro
    ports:
      - "8000:80"
    command:
      /bin/bash -c "nginx -g 'daemon off;'"
