# Generated by Django 3.1.4 on 2021-01-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20201230_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='avatar',
            field=models.ImageField(upload_to='static/spaces'),
        ),
    ]
